#!/usr/bin/env Rscript

files <- commandArgs(trailing = TRUE)
renv_schema <- '{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "See https://github.com/rstudio/renv",
  "title": "renv.lock file.",
  "description": "A schema for renv.lock files generated by {renv}",
  "type": "object",
  "properties": {
    "R": {
      "type": "object",
      "properties": {
        "Version": {
          "description": "The version of R used.",
          "type": "string"
        },
        "Repositories": {
          "description": "The R repositories used in this project.",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "Name": {
                "type": "string"
              },
              "URL": {
                "type": "string",
                "format": "uri"
              }
            },
            "required": ["Name", "URL"]
          }
        }
      },
      "required": ["Version", "Repositories"]
    },
     "Bioconductor": {
      "type": "object",
      "properties": {
        "Version": {
          "type": "string"
        }
      },
      "required": ["Version"]
    },
    "Packages": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "Package": {
            "description": "The package name.",
            "type": "string",
            "examples": ["ggplot2", "dplyr"]
          },
          "Version": {
            "description": "The package version.",
            "type": "string",
            "examples": ["1.0.0", "3.4.6"]
          },
          "Source": {
            "description": "The location from which this package was retrieved.",
            "type": "string",
            "examples": ["Repository", "Bioconductor"]
          },
          "Repository": {
            "description": "The name of the repository (if any) from which this package was retrieved.",
            "type": "string",
            "examples": ["CRAN"]
          },
          "Hash": {
            "description": "(Optional) A unique hash for this package, used for package caching.",
            "type": "string",
            "pattern": "^[a-fA-F0-9]{32}$"
          },
          "RemoteType": {
            "description": "Type of the remote, typically written for packages installed by the devtools, remotes and pak packages.",
            "type": "string",
            "examples": ["standard", "github"]
          },
          "RemoteHost": {
            "description": "Host for the remote.",
            "type": "string",
            "format": "uri",
            "examples": ["api.github.com"]
          },
          "RemoteUsername": {
            "description": "Username for the remote.",
            "type": "string"
          },
          "RemoteRepo": {
            "description": "Repositories for the package.",
            "type": "string",
            "examples": [
              "https://cran.rstudio.com",
              "https://cloud.r-project.org"
            ]
          },
          "RemoteRepos": {
            "description": "Repositories for the package.",
            "type": "string",
            "format": "uri",
            "examples": [
              "https://cran.rstudio.com",
              "https://cloud.r-project.org"
            ]
          },
          "RemoteRef": {
            "description": "Name of the packages.",
            "type": "string"
          },
          "RemotePkgRef": {
            "description": "Name of the packages.",
            "type": "string"
          },
          "RemotePkgPlatform": {
            "description": "Architecture/platform of the remote.",
            "type": "string",
            "examples": ["aarch64-apple-darwin20"]
          },
          "RemoteSha": {
            "description": "Version number of the package.",
            "type": "string"
          },
          "Requirements": {
            "description": "Dependencies of the package.",
            "type": "array",
            "items": {
              "type": "string"
            },
            "examples": [
              [ 
                "R",
                "jsonlite",
                "lifecycle",
                "magrittr",
                "stringi"
              ],
              [
                "R6",
                "Rcpp",
                "later",
                "magrittr",
                "rlang",
                "stats"
              ]
            ]
          }
        },
        "required": ["Package", "Version", "Source"]
      }
    }
  },
  "required": ["R", "Packages"]
}'

validate_renv_lock <- function(renv_path, renv_lock_schema) {
  renv_json <- readr::read_file(renv_path)

  jsonvalidate::json_validate(
    renv_json,
    renv_lock_schema,
    engine  = "ajv",
    greedy  = TRUE,
    error   = TRUE,
    verbose = TRUE
  )
}

out <- lapply(files, function(path) {
  is_renv_lock <- grepl("^.*renv\\.lock$", path)
  if (is_renv_lock) {
    tryCatch(
      validate_renv_lock(path, renv_schema),
      error = function(error) {
        cat(c("{renv} lock file at path", path, "failed validation. Full context:\n"))
        stop(conditionMessage(error), call. = FALSE)
      }
    )
  }
})
