#!/usr/bin/env Rscript

files <- commandArgs(trailing = TRUE)
renv_schema <- '{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "renv.lock file.",
  "description": "A schema for renv.lock files generated by {renv}",
  "type": "object",
  "properties": {
    "R": {
      "type": "object",
      "properties": {
        "Version": {
          "type": "string"
        },
        "Repositories": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "Name": {
                "type": "string"
              },
              "URL": {
                "type": "string",
                "format": "uri"
              }
            },
            "required": ["Name", "URL"]
          }
        }
      },
      "required": ["Version", "Repositories"]
    },
    "Packages": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "Package": {
            "type": "string"
          },
          "Version": {
            "type": "string"
          },
          "Source": {
            "type": "string"
          },
          "Repository": {
            "type": "string"
          },
          "Hash": {
            "type": "string",
            "pattern": "^[a-fA-F0-9]{32}$"
          },
          "RemoteType": {
            "type": "string"
          },
          "RemoteHost": {
            "type": "string",
            "format": "uri"
          },
          "RemoteUsername": {
            "type": "string"
          },
          "RemoteRepo": {
            "type": "string"
          },
          "RemoteRef": {
            "type": "string"
          },
          "RemoteSha": {
            "type": "string",
             "pattern": "^[a-fA-F0-9]{40}$"
          },
          "Requirements": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": ["Package", "Version", "Source", "Hash"]
      }
    }
  },
  "required": ["R", "Packages"]
}'

validate_renv_lock <- function(renv_path, renv_lock_schema) {
  renv_json <- readr::read_file(renv_path)

  jsonvalidate::json_validate(
    renv_json,
    renv_lock_schema,
    engine  = "ajv",
    greedy  = TRUE,
    error   = TRUE,
    verbose = TRUE
  )
}

out <- lapply(files, function(path) {
  is_renv_lock <- grepl("^.*renv\\.lock$", path)
  if (is_renv_lock) {
    tryCatch(
      validate_renv_lock(path, renv_schema),
      error = function(error) {
        cat(c("{renv} lock file at path", path, "failed validation. Full context:\n"))
        stop(conditionMessage(error), call. = FALSE)
      }
    )
  }
})
